### ISSUE TITLE
Error given on webinterface

### ISSUE THREAD

**Issue by cosminstefane** [artdevision/minestat#1]
I am getting this error when try to connect to host_ip/cabinet

UnexpectedValueException
The stream or file "/var/www/html/storage/logs/laravel-2019-04-12.log" could not be opened: failed to open stream: Permission denied

Also seems that one docker keeps restarting:

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                          PORTS                                                NAMES
edbbf3f8bc9d        minestat_php_srv         "/var/www/html/init.…"   2 hours ago         Restarting (0) 33 seconds ago                                                        minestat_php_srv_run_1a73ccc084fe

**Comment by artdevision** [comment]
chmod -R 777 storage

**Comment by artdevision** [comment]
> I am getting this error when try to connect to host_ip/cabinet
> 
> UnexpectedValueException
> The stream or file "/var/www/html/storage/logs/laravel-2019-04-12.log" could not be opened: failed to open stream: Permission denied
> 
> Also seems that one docker keeps restarting:
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> edbbf3f8bc9d minestat_php_srv "/var/www/html/init.…" 2 hours ago Restarting (0) 33 seconds ago minestat_php_srv_run_1a73ccc084fe

**Comment by artdevision** [comment]
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> edbbf3f8bc9d minestat_php_srv "/var/www/html/init.…" 2 hours ago Restarting (0) 33 seconds ago minestat_php_srv_run_1a73ccc084fe

Can you trace cd docker && docker-compose logs

**Comment by cosminstefane** [comment]
One error I see: 
mongodb_srv_1  | Welcome to the Bitnami mongodb container
mongodb_srv_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb_srv_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb_srv_1  |
mongodb_srv_1  | nami    INFO  Initializing mongodb
mongodb_srv_1  | mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb_srv_1  | mongodb INFO  ==> Configuration files found...
mongodb_srv_1  | mongodb INFO  ==> Creating root user...
mongodb_srv_1  | mongodb WARN  ==> You are mounting a configuration file and setting the mongodb password or root password.
mongodb_srv_1  | mongodb WARN  ==> Remember to enable authentication in your config file for those password to be valid.
mongodb_srv_1  | mongodb INFO  ==> Creating minestat user...
mongodb_srv_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb'

**Comment by artdevision** [comment]
I see) I fix it in a few minutes and commit )
Your way to fix it:
`cd docker
chmod -R 777 data
docker-compose down`
and then
`docker-compose up -d`

after create user like in manual:
`docker-compose run php_srv /bin/bash
php /var/www/html/artisan user:create your@email.com
`
After type and confirm password type `exit`
Done

**Comment by cosminstefane** [comment]
Now I run into other errors...Better wait for your update and will start from scratch...

**Comment by artdevision** [comment]
Can you trace an error?

**Comment by cosminstefane** [comment]
I did a git pull, I see you updated 1h ago, seems related to that:
On web interface I get:

**Comment by artdevision** [comment]
Thanks, I commit fixes

**Comment by artdevision** [comment]
You may pull chanches

**Comment by cosminstefane** [comment]
Finally it's working now, but I still had to chmod -R 777 data, otherwise one docker restating constantly

**Comment by artdevision** [comment]
Thanks

**Comment by cosminstefane** [comment]
New error, this used to happen before after restarting one of the miners, but later just work as expected, now it seems I cannot get rid of it no matter what I did (even reinstalling it).
Undefined index: default_watts (View: /var/www/html/resources/views/rigs/table.blade.php) (View: /var/www/html/resources/views/rigs/table.blade.php)

**Comment by artdevision** [comment]
I fix it in new commit
